# Generated by Django 4.2.4 on 2024-04-23 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=255)),
                ('quantidade', models.CharField(max_length=255)),
                ('especificacoestecnicas', models.CharField(max_length=255)),
                ('motivo', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categorias')),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='desenvolvedor',
        ),
        migrations.DeleteModel(
            name='Desenvolvedor',
        ),
        migrations.DeleteModel(
            name='Jogo',
        ),
    ]
